steps:
 - id: test
   name: "gcr.io/cloud-builders/go"
   args: ["test","./main"]
   env: ["GOPATH=."]

 - id: run
   name: "gcr.io/cloud-builders/go"
   args: ["run","./main/main.go"]
   env: ["GOPATH=."]

 - id: build
   name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'gcr.io/[PROJECT_ID]/go-test', '.' ]

 - id: push
   name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/[PROJECT_ID]/go-test']